### ISSUE TITLE
眼睛戴墨镜遮住了怎么还有landmark 和位置 ？

### ISSUE THREAD

**Issue by FaceAISDK** [Reathin/Sample-Android#1]
怎么能知道眼睛和嘴 被墨镜和口罩等东西遮住了

![image](https://github.com/Reathin/Sample-Android/assets/15169396/2d2ffb47-684c-4b36-b151-113818f5a2bc)

怎么能知道眼睛和嘴 被墨镜和口罩等东西遮住了

**Comment by Reathin** [comment]
这个库目前是达不到这种效果的
